platforms = [{'aliases': 'Gameboy\nGB', 'guid': '3045-3', 'id': 3, 'name': 'Game Boy'},
             {'aliases': 'Game Boy Advance SP\r\nGameboy Advance\r\nGBA\r\nGame Boy Player\r\nGBA SP\r\nGame Boy micro',
                 'guid': '3045-4', 'id': 4, 'name': 'Game Boy Advance'},
             {'aliases': 'Sega Mega Drive\nSega Genesis\nSega Nomad',
                 'guid': '3045-6', 'id': 6, 'name': 'Genesis'},
             {'aliases': 'Super NES\r\nSuper Famicom\r\nSFC\r\nSNES', 'guid': '3045-9',
                 'id': 9, 'name': 'Super Nintendo Entertainment System'},
             {'aliases': 'Macintosh\r\nOSX\r\nOS X',
              'guid': '3045-17', 'id': 17, 'name': 'Mac'},
             {'aliases': 'PSP\r\nPSPgo\r\nPSP Go', 'guid': '3045-18',
              'id': 18, 'name': 'PlayStation Portable'},
             {'aliases': 'PS2', 'guid': '3045-19',
                 'id': 19, 'name': 'PlayStation 2'},
             {'aliases': '360\r\nXenon\r\nx360',
              'guid': '3045-20', 'id': 20, 'name': 'Xbox 360'},
             {'aliases': 'Nintendo\r\nFamicom\r\nFamily Computer\r\nControl Deck\r\nFC\r\nFDS\r\nNES',
              'guid': '3045-21', 'id': 21, 'name': 'Nintendo Entertainment System'},
             {'aliases': 'PS1\r\nPSX\r\nSony PlayStation\r\nNet Yaroze\r\nPocketStation\r\nPSone',
              'guid': '3045-22', 'id': 22, 'name': 'PlayStation'},
             {'aliases': 'GCN\nNGC\nGC\nProject Dolphin\nPanasonic Q\nNintendo GameCube',
              'guid': '3045-23', 'id': 23, 'name': 'GameCube'},
             {'aliases': None, 'guid': '3045-32', 'id': 32, 'name': 'Xbox'},
             {'aliases': 'PS3', 'guid': '3045-35',
                 'id': 35, 'name': 'PlayStation 3'},
             {'aliases': 'Nintendo Wii\nRevolution\nWii Mini',
              'guid': '3045-36', 'id': 36, 'name': 'Wii'},
             {'aliases': 'Sega Dreamcast', 'guid': '3045-37',
                 'id': 37, 'name': 'Dreamcast'},
             {'aliases': 'N64\nProject Reality\nUltra 64',
              'guid': '3045-43', 'id': 43, 'name': 'Nintendo 64'},
             {'aliases': 'Nitro\r\nDual Screen\r\nDevelopers System\r\nDS Lite\r\nDSi\r\nDSi XL\r\nDSi LL',
              'guid': '3045-52', 'id': 52, 'name': 'Nintendo DS'},
             {'aliases': 'Gameboy Color\nGame Boy Colour\nGameboy Colour\nGBC',
              'guid': '3045-57', 'id': 57, 'name': 'Game Boy Color'},
             {'aliases': 'iPod Classic', 'guid': '3045-72', 'id': 72, 'name': 'iPod'},
             {'aliases': 'Arcades\nCoin-op\nCoin-ops\n',
              'guid': '3045-84', 'id': 84, 'name': 'Arcade'},
             {'aliases': 'Personal Computer\r\nMicrosoft Windows\r\nDOS\r\nIBM\r\nIBM Jr.\r\nPC Booter',
              'guid': '3045-94', 'id': 94, 'name': 'PC'},
             {'aliases': 'iPod Touch\niOS\niConsoles',
              'guid': '3045-96', 'id': 96, 'name': 'iPhone'},
             {'aliases': 'Nintendo 3DS XL\r\nNintendo 3DS LL\r\n3DS\r\n3DS XL\r\n3DS LL\r\nNintendo 2DS\r\n2DS',
              'guid': '3045-117', 'id': 117, 'name': 'Nintendo 3DS'},
             {'aliases': 'Google Android\r\nDroid',
              'guid': '3045-123', 'id': 123, 'name': 'Android'},
             {'aliases': 'Next Generation Portable\nPSV\nPS Vita\nVita\nNGP',
              'guid': '3045-129', 'id': 129, 'name': 'PlayStation Vita'},
             {'aliases': 'Project Café\nProject Cafe\nWiiU\nWii-U\nNintendo Wii U',
              'guid': '3045-139', 'id': 139, 'name': 'Wii U'},
             {'aliases': 'Facebook\r\nWorld Wide Web\r\nIn-Browser\r\nFlash Games\r\nJava Games\r\nHTML5 Games\r\nChrome web store',
              'guid': '3045-140', 'id': 140, 'name': 'Browser'},
             {'aliases': 'Xbox Durango\r\nXONE\r\nXBONE\r\nXbox 1\r\nXB1\r\nXbox One S\r\nXbox One X\r\nProject Scorpio',
              'guid': '3045-145', 'id': 145, 'name': 'Xbox One'},
             {'aliases': 'PS4\r\nOrbis\r\nPS4 Pro', 'guid': '3045-146',
              'id': 146, 'name': 'PlayStation 4'},
             {'aliases': 'Ubuntu\r\nGNU/Linux',
                 'guid': '3045-152', 'id': 152, 'name': 'Linux'},
             {'aliases': 'New Nintendo 3DS XL\r\nNew Nintendo 3DS LL\r\nN3DS\r\nNew 3DS\r\nNew Nintendo 2DS XL\r\nNew Nintendo 2DS LL\r\nN2DSLL\r\nN2DSXL',
              'guid': '3045-156', 'id': 156, 'name': 'New Nintendo 3DS'},
             {'aliases': 'Nintendo NX\nNintendo Switch Lite',
              'guid': '3045-157', 'id': 157, 'name': 'Nintendo Switch'},
             {'aliases': None, 'guid': '3045-175',
                 'id': 175, 'name': 'Google Stadia'},
             {'aliases': 'PS5\nPlayStation 5 Digital Edition',
              'guid': '3045-176', 'id': 176, 'name': 'PlayStation 5'},
             {'aliases': None, 'guid': '3045-177',
                 'id': 177, 'name': 'Oculus Quest'},
             {'aliases': 'Xbox 4\nProject Scarlett\nXbox\nLockhart\nAnaconda\nXbox Series S\nXSX',
                 'guid': '3045-179', 'id': 179, 'name': 'Xbox Series X|S'},
             {'id': 0, 'name': 'All'}]
